# Generated by Django 4.0.6 on 2022-07-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, default='', max_length=50)),
                ('weight', models.CharField(blank=True, default='', max_length=50)),
                ('marital_status', models.CharField(blank=True, default='', max_length=50)),
                ('dish', models.CharField(blank=True, default='', max_length=50)),
                ('movie', models.CharField(blank=True, default='', max_length=50)),
                ('song', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_login', models.IntegerField(blank=True, default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('sex', models.CharField(blank=True, choices=[('1', 'mężczyzna'), ('2', 'kobieta')], max_length=1, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('personal_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.personaldetails')),
                ('puls', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.puls')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
